{{ if .Values.runtime.distributed_mode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- range .Values.controller.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
  name: setagaya-controller-{{ .Values.context }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- range .Values.controller.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range .Values.controller.labels }}
        {{ .key }}: {{ .value }}
        {{- end }}
      {{- if .Values.controller.annotations }}
      annotations:
        {{- range .Values.controller.annotations }}
        {{.key }}: {{.value }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.repository }}{{ .Values.controller.image.name }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        name: setagaya-sc
        resources:
          requests:
            cpu: {{ .Values.controller.resources.requests.cpu | quote }}
            memory: {{ .Values.controller.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.controller.resources.limits.cpu | quote }}
            memory: {{ .Values.controller.resources.limits.memory | quote }}
        env:
        {{- range .Values.controller.envvars }}
        - name: {{ .key | quote }}
          value: {{ .value | quote }}
        {{- end }}
        volumeMounts:
        - name: setagaya-config
          mountPath: /config.json
          subPath: config.json
        {{- if not .Values.runtime.executors.in_cluster }}
        - name: kubeconfig-volume
          mountPath: /root/.kube/config
          subPath: config
        {{- end }}
        {{- if eq .Values.runtime.object_storage.provider "gcp" }}
        - name: setagaya-gcp-auth
          mountPath: /auth/setagaya-gcp.json
          subPath: setagaya-gcp.json
        {{- end }}
      dnsPolicy: ClusterFirst
      serviceAccount: setagaya
      serviceAccountName: setagaya
      {{- if .Values.image_pull_secrets }}
      imagePullSecrets:
        {{- range .Values.image_pull_secrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      volumes:
      - name: setagaya-config
        configMap:
          name: setagaya-config-{{ .Values.context }}
      {{- if not .Values.runtime.executors.in_cluster }}
      - name: kubeconfig-volume
        configMap:
          defaultMode: 420
          name: setagaya-token-{{ .Values.cluster_name }}
      {{- end }}
      {{- if eq .Values.runtime.object_storage.provider "gcp" }}
      - name: setagaya-gcp-auth
        secret:
          secretName: setagaya-auth-keys-gcp
      {{- end }}
{{ end }}
