run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - ui/static/dist
    - ui/static/js/lib
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-line: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/hveda/setagaya
    
  golint:
    min-confidence: 0
    
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
        
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Printf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf
          
  lll:
    line-length: 120
    
  maligned:
    suggest-new: true
    
  misspell:
    locale: US
    
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
    
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
        
  staticcheck:
    go: "1.23"
    checks: ["all"]
    
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked
      - G204  # Subprocess launched with variable
    config:
      global:
        nosec: false
        "#nosec": "#nosec"
        show-ignored: false
        
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        
    - path: main\.go
      linters:
        - gochecknoinits
        
    - text: "weak cryptographic primitive"
      linters:
        - gosec
        
    - text: "Use of builtin function make"
      linters:
        - gosec
        
    - text: "G304"  # File path provided as taint input
      linters:
        - gosec
        
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false