# yamllint configuration file
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Allow some indentation flexibility
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Be more flexible with comments
  comments:
    min-spaces-from-content: 1

  # Allow empty values (common in Kubernetes)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Allow truthy values (common in Kubernetes)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

  # Allow brackets for lists
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow some document start flexibility
  document-start:
    present: false

  # Octal values (often used in file permissions)
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

ignore: |
  # Ignore generated files
  **/templates/*.yaml
  **/charts/*/templates/*.yaml
  # Ignore vendored files
  vendor/
  # Ignore specific files that may have different formatting requirements
  setagaya/install/setagaya/templates/configmap.yaml
