apiVersion: v1
kind: Service
metadata:
  name: {{ include "honryu.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honryu.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "honryu.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
