{
 "title": "setagaya",
 "time": { "from": "2020-04-01T07:46:39.000Z", "to": "2020-04-01T07:51:45.000Z" },
 "templating": {
  "list": [
   { "name": "collectionID", "label": "Collection ID", "query": "label_values(collection_id)" },
   { "name": "planID", "label": "Plan ID", "query": "label_values(plan_id)" },
   { "name": "label", "label": "Label", "query": "label_values(label)" },
   { "name": "runID", "label": "Run ID", "query": "label_values(run_id)" }
  ]
 },
 "panels": [
  { "title": "Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2xx percentage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(setagaya_status_counter{run_id=\"$runID\", status=~\"2..\"}) by (run_id) / sum(setagaya_status_counter{run_id=\"$runID\"}) by (run_id))*100"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(setagaya_status_counter{run_id=\"$runID\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Overall latency for collection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(setagaya_latency_collection_sum{run_id=\"$runID\"}[2s])) by (run_id)) / (sum(rate(setagaya_status_counter{run_id=\"$runID\"}[2s])) by (run_id))",
     "legendFormat": "Average"
    },
    {
     "expr": "setagaya_latency_collection{run_id=\"$runID\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(setagaya_status_counter{run_id=\"$runID\"})"
    }
   ]
  },
  {
   "title": "Engines",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(setagaya_threads_gauge{run_id=\"$runID\"})"
    }
   ]
  },
  {
   "title": "Overall QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(setagaya_status_counter{run_id=\"$runID\"}[30s])) by (run_id)",
     "legendFormat": "{{run_id}}"
    },
    {
     "expr": "sum(rate(setagaya_status_counter{run_id=\"$runID\"}[30s])) by (plan_id)",
     "legendFormat": "{{plan_id}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(setagaya_threads_gauge{run_id=\"$runID\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Detailed response stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(setagaya_status_counter{run_id=\"$runID\"}) by (label, plan_id, status)"
    }
   ]
  },
  {
   "title": "Errors over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(setagaya_status_counter{run_id=\"$runID\", status!=\"200\"}[2s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Plan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx percentage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\", status=~\"2..\"}) by (plan_id) / sum(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"}) by (plan_id))*100"
      }
     ]
    },
    {
     "title": "Response Status",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 11, "x": 3, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency percentile of plan",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(setagaya_latency_plan_sum{run_id=\"$runID\", plan_id=\"$planID\"}[2s])) by (plan_id)) / (sum(rate(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"}[2s])) by (plan_id))",
       "legendFormat": "Average"
      },
      {
       "expr": "setagaya_latency_plan{plan_id=\"$planID\", run_id=\"$runID\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"})"
      }
     ]
    },
    {
     "title": "Engines",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(setagaya_threads_gauge{run_id=\"$runID\", plan_id=\"$planID\"})"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "QPS" }
     ],
     "targets": [
      {
       "expr": "sum(rate(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"}[30s])) by (plan_id)",
       "legendFormat": "{{plan_id}}"
      },
      {
       "expr": "sum(rate(setagaya_status_counter{run_id=\"$runID\", plan_id=\"$planID\"}[30s])) by (label)",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(setagaya_threads_gauge{run_id=\"$runID\", plan_id=\"$planID\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Errors over time",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(increase(setagaya_status_counter{run_id=\"$runID\", status!=\"200\", plan_id=\"$planID\"}[2s])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx percentage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(setagaya_status_counter{run_id=\"$runID\", label=\"$label\", status=~\"2..\"}) by (label) / sum(setagaya_status_counter{run_id=\"$runID\", label=\"$label\"}) by (label))*100"
      }
     ]
    },
    {
     "title": "Response Status",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 11, "x": 3, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(setagaya_status_counter{run_id=\"$runID\", label=\"$label\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency Percentile of  label",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(setagaya_latency_label_sum{run_id=\"$runID\", label=\"$label\"}[2s])) by (label)) / (sum(rate(setagaya_status_counter{run_id=\"$runID\", label=\"$label\"}[2s])) by (label))",
       "legendFormat": "Average"
      },
      {
       "expr": "setagaya_latency_label{label=\"$label\", run_id=\"$runID\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(setagaya_status_counter{run_id=\"$runID\", label=\"$label\"})"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "QPS" }
     ],
     "targets": [
      {
       "expr": "sum(rate(setagaya_status_counter{run_id=\"$runID\", label=\"$label\"}[30s])) by (label)",
       "legendFormat": "{{url}}"
      }
     ]
    }
   ]
  }
 ]
}