# golangci-lint configuration for v2.4.0 compatibility
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      # Use colored text output (default format)
      colors: true
      print-linter-name: true
      print-issued-lines: true

linters:
  enable:
    # Essential Go linters
    - staticcheck
    - govet
    - ineffassign
    - unused
    - errcheck

  disable:
    # Disabled linters (can be re-enabled gradually)
    - depguard # disable for now
    - dogsled # disable for now
    - dupl # disable for now
    - gochecknoinits # disable for now - many legitimate init functions
    - goconst # disable for now
    - gocyclo # disable for now
    - gosec # disable for now
    - lll # disable for now - line length not critical
    - misspell # disable for now
    - nakedret # disable for now
    - revive # disable for now - too many comment requirements
    - gocognit # disable for now
    - prealloc # disable for now
    - nolintlint # disable for now
    - unparam # disable for now
    - bodyclose # disable for now - many false positives
    - unconvert # disable for now
    - whitespace # disable for now

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Disable field alignment warnings (cosmetic, low impact)

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204 # Subprocess launched with function call as argument or cmd arguments
      - G304 # File path provided as taint input
