# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  goimports:
    local-prefixes: github.com/hveda/Setagaya

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  depguard:
    rules:
      main:
        deny:
          - pkg: 'github.com/pkg/errors'
            desc: 'use standard library errors package'

  misspell:
    locale: US

  lll:
    line-length: 120

  gofmt:
    simplify: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204 # Subprocess launched with function call as argument or cmd arguments
      - G304 # File path provided as taint input

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: var-naming

linters:
  enable:
    - gofmt
    - goimports
    - staticcheck
    - typecheck

  disable:
    - deadcode # deprecated in favor of unused
    - structcheck # deprecated in favor of unused
    - varcheck # deprecated in favor of unused
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - exportloopref # deprecated since Go 1.22
    - depguard # disable for now
    - dogsled # disable for now
    - dupl # disable for now
    - gochecknoinits # disable for now - many legitimate init functions
    - goconst # disable for now
    - gocyclo # disable for now
    - gosec # disable for now
    - lll # disable for now - line length not critical
    - misspell # disable for now
    - nakedret # disable for now
    - revive # disable for now - too many comment requirements
    - gocognit # disable for now
    - prealloc # disable for now
    - nolintlint # disable for now
    - unparam # disable for now
    - bodyclose # disable for now - many false positives
    - govet # disable for now - too many field alignment warnings
    - ineffassign # disable for now
    - unconvert # disable for now
    - whitespace # disable for now
    - errcheck # disable for now - many intentionally ignored errors
    - gosimple # disable for now - minor style issues
    - unused # disable for now - many intentionally unused items for future use

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linter issues
    - text: 'weak cryptographic primitive'
      linters:
        - gosec

    # Exclude shadow warnings for common variable names
    - text: 'shadow: declaration of "err"'
      linters:
        - govet

    # Exclude defer close errors for database cleanup (low risk)
    - text: 'Error return value.*Close.*not checked'
      linters:
        - errcheck

    # Exclude errors for database scan operations in model layer (handled at higher level)
    - path: model/
      text: 'Error return value.*Scan.*not checked'
      linters:
        - errcheck

    # Exclude last insert ID checks (often intentionally ignored)
    - text: 'Error return value.*LastInsertId.*not checked'
      linters:
        - errcheck

    # Exclude type assertions for known internal types
    - text: 'Error return value is not checked.*\.\('
      linters:
        - errcheck
      source: '^\s*\w+\s*:?=.*\.\([^)]+\)'

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
