# Minimal golangci-lint configuration compatible with v2.x
# Most configuration is handled via command-line arguments in GitHub Actions

version: "2"

run:
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
