# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  goimports:
    local-prefixes: github.com/hveda/Setagaya

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use standard library errors package"

  misspell:
    locale: US

  lll:
    line-length: 120

  gofmt:
    simplify: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204 # Subprocess launched with function call as argument or cmd arguments
      - G304 # File path provided as taint input

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: exported
        severity: error
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: package-comments
        severity: warning

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gocognit
    - prealloc
    - exportloopref
    - nolintlint

  disable:
    - deadcode # deprecated in favor of unused
    - structcheck # deprecated in favor of unused
    - varcheck # deprecated in favor of unused
    - maligned # deprecated
    - interfacer # deprecated  
    - scopelint # deprecated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow warnings for common variable names
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
