// Package telemetry renders the trace-context headers a run's generated load
// carries, so a target's own APM can be filtered down to exactly one Honryu run.
//
// Honryu propagates; it does not trace. There are no Honryu spans and no trace
// pipeline (resolved decision #10): the headers below are the entire surface,
// and everything queryable about the run's identity rides in W3C `baggage`
// rather than a bespoke header, because baggage is the standard sibling of
// traceparent for exactly this and several OTel-based APM SDKs already promote
// its entries to span attributes.
//
// The `traceparent` sampled flag is always 00. Sampling on would force a
// compliant target SDK to export every request of a run as spans under one
// reused trace id -- distorting the load being measured and producing an
// unrenderable trace -- so the renderer cannot express any other value.
//
// Pure domain: formatting only, deterministic, no randomness and no I/O. The
// random ids themselves are generated by the caller (crypto/rand in
// lifecycleapp) and handed in as plain values, keeping this package table-
// testable.
package telemetry

import (
	"fmt"
	"strconv"
	"strings"
)

// TraceContext is the per-run trace identity a Deploy generates once and every
// scenario and shard of that deploy shares. TraceID is 32 lowercase hex (a
// W3C trace id), ParentID is 16 lowercase hex (a W3C parent-span id).
type TraceContext struct {
	TraceID  string
	ParentID string
}

// Identity is everything about a run that its requests should be findable by
// in a customer's APM. The fields mirror the Execution aggregate's own
// identity; TenantID is a pointer because tenant-less executions predate
// tenancy and must render without a tenant entry rather than an empty one.
type Identity struct {
	TenantID  *int64
	ProjectID int64
	// ExecutionID is the id of the execution generating this load.
	ExecutionID int64
	// RunCorrelationID is the trace id from TraceContext: one generated value
	// serves as both the wire trace id and the stored correlation id, so the
	// two can never disagree.
	RunCorrelationID string
}

// Headers renders the trace-context headers generated load carries:
//
//	traceparent: 00-<trace id>-<parent id>-00   (W3C, sampled flag always off)
//	baggage:     honryu.tenant=…,honryu.service=…,honryu.execution=…,honryu.run=…
//
// A nil TenantID omits the honryu.tenant entry rather than rendering it empty.
// Both values are identical for every scenario and shard of one Deploy call:
// one deploy is one run in practice, so one identity covers all of it.
func Headers(tc TraceContext, id Identity) map[string]string {
	baggage := make([]string, 0, 4)
	if id.TenantID != nil {
		baggage = append(baggage, "honryu.tenant="+strconv.FormatInt(*id.TenantID, 10))
	}
	baggage = append(baggage,
		"honryu.service="+strconv.FormatInt(id.ProjectID, 10),
		"honryu.execution="+strconv.FormatInt(id.ExecutionID, 10),
		"honryu.run="+id.RunCorrelationID,
	)
	return map[string]string{
		"traceparent": fmt.Sprintf("00-%s-%s-00", tc.TraceID, tc.ParentID),
		"baggage":     strings.Join(baggage, ","),
	}
}
