name: github pages

on:
  push:
    branches:
      - master

# Ensure only one GitHub Pages deployment runs at a time
concurrency:
  group: gh-pages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          #mdbook-version:
          mdbook-version: 'latest'

      - run: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
